#!/usr/bin/env bash
#Transfer file to a server
if [ "$#" -lt 3 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
     scp "$1" "$3"@"$2":~/"$1"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/"$1"
fi
