#!/usr/bin/env bash
#installing Nginx on the server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
