#!/usr/bin/env bash
#installing Nginx and redirecting with 301
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
redirection="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "531 $redirection" /etc/nginx/sites-available/default
sudo service nginx restart
