#!/usr/bin/env bash
# Install haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y update
loadb_config="\\\nfrontend basic_fe\n\tmode http\n\tbind *:80\n\tdefault_backend api_servers\n\nbackend api_servers\n\tmode http\n\tbalance roundrobin\n\tserver s1 100.25.198.255:80\n\tserver s2 35.175.65.128:80"
sed -i "34i $loadb_config" /etc/haproxy/haproxy.cfg
sudo service nginx restart