#!/usr/bin/env bash
# This is a while loop to print Best School 10 times with some caveats
i=1
while [ $i -le 20 ];
do
    case $i in
	4)
	    echo $i
	    echo "bad luck from China"
	    ((i++));;
	9)
	    echo $i
	    echo "bad luck from Japan"
	    ((i++));;
	17)
	    echo $i
	    echo "bad luck from Italy"
	    ((i++));;
	*)
	    echo $i
	    ((i++))
    esac
done
